project_id: kdv-pomelo
base_path: /src/languages
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: en-US/commands/utility.json
    translation: '%two_letters_code%/commands/utility.json'
  - source: en-US/arguments.json
    translation: '%two_letters_code%/arguments.json'
  - source: en-US/errors.json
    translation: '%two_letters_code%/errors.json'
  - source: en-US/messages.json
    translation: '%two_letters_code%/messages.json'
  - source: en-US/settings.json
    translation: '%two_letters_code%/settings.json'
