services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - appnet
  bun:
    image: "oven/bun:latest"
    working_dir: "/home/bun/pom"
    restart: unless-stopped
    volumes:
      - ./:/home/bun/pom
    command: sh -c "bun install -D typescript && bun run build && bun run start"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
